### ISSUE TITLE
Can't hear other players

### ISSUE THREAD

**Issue by jakeb072001** [Qlevine/DeadAndBored#1]
After a player dies, players wont be able to hear the voice of any other players that have also died.

It seems the voice isn't coming from the player during this as one time this happened I heard my friends voice faintly somewhere else in the dungeon behind me even though my friend was in front on me.

**Comment by Qlevine** [comment]
What other mods did you have installed? Do you have a modpack I could test with?

**Comment by Qlevine** [comment]
I think I fixed this in the newest patch

**Comment by jakeb072001** [comment]
Thanks, I'll check it out when I'm on with my friends again. If it still doesn't I can maybe try do a bit of testing and figure out more info but hopefully it's all fixed now.
