### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by VanilaBOI** [Qlevine/DeadAndBored#3]
Hey, Love the mod, works great

I would just like to keep it a secret from my friends, therefor could you make a config that turns of the tooltip that says Talk as Monster.

Also(I know this is a really big request) I'd love this mod to work with the control company mod, so that you can talk through the monster you are controlling.

Anyways keep up the good work!!

**Comment by Qlevine** [comment]
Ok just uploaded the first request as that was pretty easy. As for the control company mod, I haven't tried that one yet. I need to see how it works before I see if its something I can add this to. Thanks for the feedback!

**Comment by VanilaBOI** [comment]
Thanks for adding that but I also have another request
My dead friends can hear me try to talk as a monster: Could you make it so as long as you are talking as a monster it mutes your death chat mic

**Comment by Qlevine** [comment]
Ok just submitted a new patch. It as a config for this but it should default to what you suggested.

**Comment by VanilaBOI** [comment]
Hhmm.. I guess they were hearing me through the monsters.

**Comment by VanilaBOI** [comment]
It doesn't work for me. I selected an enemy they can't possibly hear and they still heard me
018d1dfc-a819-12d5-73e2-5de62f0205ad

**Comment by Qlevine** [comment]
Just uploaded a new patch that may help. If it still doesn't work, I added a debug config option which will create a ton of log messages to help me find the issue. You would need to send me that. You have to enable the debug config, otherwise it will not create the log messages.
