### ISSUE TITLE
Bug in orbit ship

### ISSUE THREAD

**Issue by ayoubsaif** [Qlevine/DeadAndBored#4]
After using enemies spoke in the orbit the voices move to out of the ship and not by proximity

**Comment by Qlevine** [comment]
Sorry I'm a little unclear what you mean. Do you mean that if the game ends, and the ship is leaving, if you use the enemy voice chat, it will not position the sound correctly?

**Comment by ShadowzOfTheDark** [comment]
I can collaborate to that particular issue you just described. Once me and my friends installed this mod we would no longer hear each other after dying. This would seem to persist until you rejoined the game. Clients that rejoined could then hear the players that were not audible before. Uncertain if you even needed to use the talk as monster feature to have your voice not work after the round ends.

**Comment by Qlevine** [comment]
So when the next round started, and you weren't dead, you could not hear each other anymore? Does it always happen, or was this rare?

**Comment by ShadowzOfTheDark** [comment]
If a person had died that round then they would not be audible anymore once they respawned.

**Comment by Qlevine** [comment]
Just submitted a new patch. Hopefully this issue is fixed.
