### ISSUE TITLE
P2P Audio Error 

### ISSUE THREAD

**Issue by EatinCheese** [Qlevine/DeadAndBored#5]
On my server, I experience an issue, resolved only by removing this mod, where occasionally server client is unable to hear another server client. Everyone else can hear both parties just fine. It's not constant, it will randomly happen partway through the game, and restarting the server will fix the issue momentarily. However, the issue isn't specifically client side as it can cause the host to be unable to hear a particular client and vice versa occasionally as well.

**Comment by Qlevine** [comment]
Just submitted a new patch. Hopefully this issue is fixed.
