### ISSUE TITLE
does it rlly need to rely on LC-API this is the only mod out of my 90 mods who uses LC-API id rather not use this api 

### ISSUE THREAD

**Issue by broilerosu** [Qlevine/DeadAndBored#6]
please

**Comment by Qlevine** [comment]
Is there a particular reason you don't want to use LC-API? Does it have bugs? I personally don't have the time to rewrite the netcode that LC-API does, and its already heavily tested, so it makes sense to use that mod.

**Comment by broilerosu** [comment]
well i dont know that much about the LC API but people in the discord server kieep advising not to use it and it pretty much everyone stopped using it i dont mind it that much i feel like it just uses resources it dont have to

**Comment by Qlevine** [comment]
If you can give me an example of a different mod that is server side that doesn't use LC-API I can take a look at what they did.

**Comment by Valafi** [comment]
Well, LC_API is no longer being developed as of yesterday. The maintainer posted [this](https://discord.com/channels/1168655651455639582/1179406408249249882/1197967263240835113) in the [LC Modding Discord server](https://discord.gg/XeyYqRdRGC).

As far as an example goes, I know the [Lock Doors](https://thunderstore.io/c/lethal-company/p/ENZ/Lock_Doors_Mod/) mod used to use LC_API but updated to not require it. Not sure about other examples off the top of my head, unfortunately.

**Comment by Valafi** [comment]
I looked through some of the mod threads in the LC Modding Discord server and found some more examples of projects that managed to remove their LC_API dependency:
* [Employee Assignments](https://thunderstore.io/c/lethal-company/p/amnsoft/EmployeeAssignments/)
* [BrackenRandomizer](https://thunderstore.io/c/lethal-company/p/Woona/BrackenRandomizer/)
* [HDLethalCompany](https://thunderstore.io/c/lethal-company/p/Sligili/HDLethalCompany/)

There are threads for these three and the Lock Doors mod in the Discord server if you wanted to try asking the authors how they went about it.

**Comment by Qlevine** [comment]
Thanks for this. Super helpful. I will look into removing the LC_API dependency this weekend.

**Comment by Qlevine** [comment]
I have removed the requirement for LC_API. I have also added config editing via in game rather than the config folder (using InputUtils).
