### ISSUE TITLE
Some teammates unable to hear others after talking as monster

### ISSUE THREAD

**Issue by mbloecke** [Qlevine/DeadAndBored#7]
Tried this mod 1/19 - 1/20 on version 1.0.5

One teammate would die and talk as a monster. More than once that teammate would then be unable to be heard by other teammates in all voice chats. Disabled the mod which fixed the issue, so we believe some part of talking as a monster is leading to others being unable to hear them for the rest of the game.

**Comment by Jogress** [comment]
+1, same thing. Tested this for ~3 rounds. It seems like 
1) players couldn't really hear "monsters speaking" (there wasn't any reaction for us constantly shouting as a monster)
2) players who tried talking as a monster semi-reliable got muted after making such attempts (and after reviving)

a shame, mod idea is really great. Maybe, it conflicts with something, like Skinwalkers...

**Comment by Qlevine** [comment]
Hello, thanks for reaching out. So I tested locally and couldn't reproduce any of this. Some things I would need to help fix the issue are what mods you were using (if you could send me a modpack that would help). Also make sure that you are pressing the "Y" key  to talk as monsters. It does not happen automatically. If you are on push to talk "T" then you have to press both "T" and "Y" in order to talk as enemy.

**Comment by Qlevine** [comment]
Also did anything unusual happen during the rounds, like someone joining late, or someone disconnecting?

**Comment by mbloecke** [comment]
018d2d81-21ab-d2ee-5459-eac5cfa60ead

Thunderstore mod list for basically all the mods. Skinwalkers was disabled when I had the issue.

We hadn't noticed any correlation in what happened to cause the issue.

1. Player died
2. Player spoke as a monster
3. sometime later noticed a couple people couldn't hear that player
4. I believe it was fixed by the other players leaving lobby and returning, so something on the other player's sides needed a reset to be fixed. 

We have a collab today, so we aren't going to test it now, but if I play again in the next day or two I can try to recreate the issue and see where it lies.

**Comment by mbloecke** [comment]
I believe we had a person or two join during, but we can test this later
when we try the mod again. One player says it was when she was voicing the
bracken that it would act up. Could be a coincidence.

People did not join between vc working for her and vc not working though.
Some people stopped hearing her without anybody joining or leaving

**Comment by mbloecke** [comment]
The one that I can think of that may class is ControlCompany.

**Comment by Qlevine** [comment]
Ok I think I found the issue. Just released 1.0.8. Let me know if you still have the issue. I also added a keybind to manually force a reset of the audio data, so if you have the issue again, the person who can't hear someone else, have them press "U" and see if that helps.
