### ISSUE TITLE
Controller bindings?

### ISSUE THREAD

**Issue by StinkySlinky1218** [Qlevine/DeadAndBored#8]
I know it's possible, but the config doesn't exactly tell me what button "JoystickButton5" is.

**Comment by StinkySlinky1218** [comment]
Other mods (example would be dedicated inventory slots) allow these bindings to be set within the game's settings menu. Maybe we could do that here too?

**Comment by Qlevine** [comment]
Hmm I couldn't find that mod. If you can send me a link to the mod that would help

**Comment by StinkySlinky1218** [comment]
I'm referring to the [flashlight](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedFlashlightSlot/) and [walkie](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedWalkieSlot/) mods. Or basically anything with the [reserved slots](https://thunderstore.io/c/lethal-company/p/FlipMods/ReservedItemSlotCore/).

**Comment by Qlevine** [comment]
Ok I added InputUtils which should give you the same functionality you see for these other mods.
Version 1.2.0
